### Get all boards
GET http://localhost:3000/boards

### Get a single board by ID
GET http://localhost:3000/boards/2

### Get all lists for a specific board
GET http://localhost:3000/boards/1/lists

### Create a new board
POST http://localhost:3000/boards
Content-Type: application/json

{
  "name": "Pads"
}

### Create a new list in a specific board
POST http://localhost:3000/boards/3/lists
Content-Type: application/json

{
  "name": "Done"
}

### Update a board by ID
PATCH http://localhost:3000/boards/2
Content-Type: application/json

{
  "name": "Lead"
}

### Delete a board by ID
DELETE http://localhost:3000/boards/3
