### Get all boards
GET http://localhost:3000/boards

### Get a single board by ID
GET http://localhost:3000/boards/1

### Create a new board
POST http://localhost:3000/boards
Content-Type: application/json

{
  "name": "Todo"
}

### Update a board by ID
PATCH http://localhost:3000/boards/1
Content-Type: application/json

{
  "name": "Doing"
}