### Get a single user by ID
GET http://localhost:3000/users/6

### Get all boards for a specific user
GET http://localhost:3000/users/1/boards

### Find all users
GET http://localhost:3000/users?email=test@mail.com

### Update a user by ID
PATCH http://localhost:3000/users/2
Content-Type: application/json

{
  "email": "test@new.com"
}

### Delete a user by ID
DELETE http://localhost:3000/users/5

