### Get a single task by ID
GET http://localhost:3000/tasks/2

### Get all subtasks for a specific task
GET http://localhost:3000/tasks/1/subtasks

### Create a new subtask in a specific task
POST http://localhost:3000/tasks/3/subtasks
Content-Type: application/json

{
  "name": "Download PSD",
  "isDone": false
}

### Update a task by ID
PATCH http://localhost:3000/tasks/3
Content-Type: application/json

{
  "name": "Conversion",
  "description": "Please expedite",
  "listId": 1
}

### Delete a task by ID
DELETE http://localhost:3000/tasks/1