### Get a single list by ID
GET http://localhost:3000/lists/2

### Get all tasks for a specific list
GET http://localhost:3000/lists/3/tasks

### Create a new task in a specific list
POST http://localhost:3000/lists/3/tasks
Content-Type: application/json

{
  "name": "To delete",
  "description": "please delete me"
}

### Update a list by ID
PATCH http://localhost:3000/lists/6
Content-Type: application/json

{
  "name": "Doing"
}

### Delete a single list by ID
DELETE http://localhost:3000/lists/7