### Get a single list by ID
GET http://localhost:3000/lists/2

### Update a list by ID
PATCH http://localhost:3000/lists/6
Content-Type: application/json

{
  "name": "Doing"
}

### Delete a single list by ID
DELETE http://localhost:3000/lists/7