### Get current logged in user
GET http://localhost:3000/auth/whoami

### Sign out user
POST http://localhost:3000/auth/signout

### Create user (signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "asdf1234"
}

### Sign in user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "asdf1234"
}